trigger:
- master
- release/*

pr:
- master
- release/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      dotnet build -c Debug -f netcoreapp2.1 Test/Mono.Cecil.Tests.csproj
      dotnet build -c Debug -f netcoreapp2.1 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj
      dotnet build -c Debug -f netcoreapp2.1 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj
      dotnet build -c Debug -f netcoreapp2.1 rocks/Test/Mono.Cecil.Rocks.Tests.csproj
    displayName: 'Build .NET Core'
  - script: |
      dotnet test --no-build -c Debug -f netcoreapp2.1 Test/Mono.Cecil.Tests.csproj
      dotnet test --no-build -c Debug -f netcoreapp2.1 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj
      dotnet test --no-build -c Debug -f netcoreapp2.1 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj
      dotnet test --no-build -c Debug -f netcoreapp2.1 rocks/Test/Mono.Cecil.Rocks.Tests.csproj
    displayName: 'Test .NET Core'
  - script: |
      dotnet build -c Debug -f net40 Test/Mono.Cecil.Tests.csproj /p:FrameworkPathOverride=/usr/lib/mono/4.0-api
      dotnet build -c Debug -f net40 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj /p:FrameworkPathOverride=/usr/lib/mono/4.0-api
      dotnet build -c Debug -f net40 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj /p:FrameworkPathOverride=/usr/lib/mono/4.0-api
      dotnet build -c Debug -f net40 rocks/Test/Mono.Cecil.Rocks.Tests.csproj /p:FrameworkPathOverride=/usr/lib/mono/4.0-api
    displayName: 'Build .NET 4.0 against Mono'
  - task: NuGetToolInstaller@0
    displayName: 'Install nuget'
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      arguments: 'install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory ./packages'
    displayName: 'Get NUnit.ConsoleRunner'
  - script: |
      mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Test/bin/Debug/net40/Mono.Cecil.Tests.dll
      mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./symbols/mdb/Test/bin/Debug/net40/Mono.Cecil.Mdb.Tests.dll
      mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./symbols/pdb/Test/bin/Debug/net40/Mono.Cecil.Pdb.Tests.dll
      mono ./packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe rocks/Test/bin/Debug/net40/Mono.Cecil.Rocks.Tests.dll
    displayName: 'Test .NET 4.0 using Mono'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      dotnet build -c Debug -f netcoreapp2.1 Test/Mono.Cecil.Tests.csproj
      dotnet build -c Debug -f netcoreapp2.1 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj
      dotnet build -c Debug -f netcoreapp2.1 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj
      dotnet build -c Debug -f netcoreapp2.1 rocks/Test/Mono.Cecil.Rocks.Tests.csproj
    displayName: 'Build .NET Core'
  - script: |
      dotnet build -c Debug -f net40 Test/Mono.Cecil.Tests.csproj
      dotnet build -c Debug -f net40 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj
      dotnet build -c Debug -f net40 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj
      dotnet build -c Debug -f net40 rocks/Test/Mono.Cecil.Rocks.Tests.csproj
    displayName: 'Build .NET 4.0'
  - script: |
      dotnet test --no-build -c Debug -f netcoreapp2.1 Test/Mono.Cecil.Tests.csproj
      dotnet test --no-build -c Debug -f netcoreapp2.1 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj
      dotnet test --no-build -c Debug -f netcoreapp2.1 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj
      dotnet test --no-build -c Debug -f netcoreapp2.1 rocks/Test/Mono.Cecil.Rocks.Tests.csproj
    displayName: 'Test .NET Core'
  - script: |
      dotnet test --no-build -c Debug -f net40 Test/Mono.Cecil.Tests.csproj
      dotnet test --no-build -c Debug -f net40 symbols/mdb/Test/Mono.Cecil.Mdb.Tests.csproj
      dotnet test --no-build -c Debug -f net40 symbols/pdb/Test/Mono.Cecil.Pdb.Tests.csproj
      dotnet test --no-build -c Debug -f net40 rocks/Test/Mono.Cecil.Rocks.Tests.csproj
    displayName: 'Test .NET 4.0'
